package runtime

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"slices"
	"strings"
	"time"

	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/util/retry"
)

var ErrArgoStopUnconfirmed = errors.New("argo CD operation stop is not confirmed")

// ApplyArgoApplication writes only the Application root. A persisted operation
// key makes an ambiguous response or worker restart resume the same sync.
func ApplyArgoApplication(ctx context.Context, client dynamic.Interface, desired *unstructured.Unstructured, children []*unstructured.Unstructured, options metav1.PatchOptions, operationID string) (*unstructured.Unstructured, error) {
	if err := ValidateArgoResources(desired, children); err != nil {
		return nil, err
	}
	if operationID == "" || options.FieldManager == "" || options.Force != nil && *options.Force {
		return nil, fmt.Errorf("GitOps requires a stable operation key and a non-forced owner")
	}
	if desired.Object["operation"] != nil {
		return nil, fmt.Errorf("GitOps operation must be generated by the executor")
	}
	if err := validateArgoProject(ctx, client, desired); err != nil {
		return nil, err
	}
	resources := client.Resource(argoApplications).Namespace(desired.GetNamespace())
	var applied, attempted *unstructured.Unstructured
	err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
		if err := CheckArgoResourceOwners(ctx, client, desired, children); err != nil {
			return err
		}
		live, err := resources.Get(ctx, desired.GetName(), metav1.GetOptions{})
		if apierrors.IsNotFound(err) {
			write := desired.DeepCopy()
			setArgoOperation(write, options.FieldManager, operationID)
			attempted = write.DeepCopy()
			applied, err = resources.Create(ctx, write, metav1.CreateOptions{FieldManager: options.FieldManager, DryRun: options.DryRun})
			return err
		}
		if err != nil {
			return err
		}
		if err := validateArgoOwner(live, options.FieldManager); err != nil {
			return err
		}
		if live.GetAnnotations()[ArgoOperationAnnotation] == operationID {
			if !reflect.DeepEqual(live.Object["spec"], desired.Object["spec"]) {
				return fmt.Errorf("GitOps operation key refers to different desired inputs")
			}
			applied = live
			return nil
		}
		if argoOperationActive(live) {
			return fmt.Errorf("GitOps Application has an unfinished operation")
		}
		write := live.DeepCopy()
		write.Object["spec"] = desired.DeepCopy().Object["spec"]
		write.SetLabels(desired.GetLabels())
		write.SetAnnotations(desired.GetAnnotations())
		setArgoOperation(write, options.FieldManager, operationID)
		attempted = write.DeepCopy()
		applied, err = resources.Update(ctx, write, metav1.UpdateOptions{FieldManager: options.FieldManager, DryRun: options.DryRun})
		return err
	})
	if err != nil && len(options.DryRun) == 0 && attempted != nil && !apierrors.IsInvalid(err) && !apierrors.IsForbidden(err) && !apierrors.IsUnauthorized(err) && !apierrors.IsBadRequest(err) && !apierrors.IsConflict(err) && !apierrors.IsAlreadyExists(err) {
		recoveryCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 15*time.Second)
		live, readErr := resources.Get(recoveryCtx, desired.GetName(), metav1.GetOptions{})
		cancel()
		if readErr != nil || validateArgoOwner(live, options.FieldManager) != nil || live.GetAnnotations()[ArgoOperationAnnotation] != operationID || attempted.GetUID() != "" && attempted.GetUID() != live.GetUID() {
			return live, fmt.Errorf("%w: sync write outcome could not be confirmed", ErrArgoStopUnconfirmed)
		}
		return stopArgoAfterError(ctx, resources, live, operationID, err)
	}
	if err != nil || len(options.DryRun) != 0 {
		return applied, err
	}
	return waitArgoOperation(ctx, resources, applied, operationID)
}

func setArgoOperation(object *unstructured.Unstructured, owner, operationID string) {
	annotations := object.GetAnnotations()
	if annotations == nil {
		annotations = map[string]string{}
	}
	annotations[ArgoOwnerAnnotation], annotations[ArgoOperationAnnotation] = owner, operationID
	object.SetAnnotations(annotations)
	object.Object["operation"] = map[string]any{
		"initiatedBy": map[string]any{"username": "soha", "automated": false},
		"info":        []any{map[string]any{"name": ArgoOperationAnnotation, "value": operationID}},
		"sync":        map[string]any{"revision": argoString(object, "spec", "source", "targetRevision"), "prune": false, "syncOptions": []any{"FailOnSharedResource=true"}},
	}
}

func validateArgoOwner(object *unstructured.Unstructured, owner string) error {
	if err := ValidateArgoApplication(object); err != nil {
		return err
	}
	if owner == "" || object.GetAnnotations()[ArgoOwnerAnnotation] != owner || object.GetUID() == "" {
		return fmt.Errorf("GitOps Application belongs to another writer; implicit adoption is disabled")
	}
	if object.GetLabels()["argocd.argoproj.io/instance"] != "" || object.GetLabels()["app.kubernetes.io/managed-by"] == "Helm" {
		return fmt.Errorf("GitOps Application is externally managed")
	}
	return nil
}

func argoOperationActive(object *unstructured.Unstructured) bool {
	phase := argoString(object, "status", "operationState", "phase")
	return object.Object["operation"] != nil || phase == "Running" || phase == "Terminating"
}

func waitArgoOperation(ctx context.Context, client dynamic.ResourceInterface, initial *unstructured.Unstructured, operationID string) (*unstructured.Unstructured, error) {
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	for {
		live, err := client.Get(ctx, initial.GetName(), metav1.GetOptions{})
		if ctx.Err() != nil {
			return stopArgoAfterError(ctx, client, initial, operationID, ctx.Err())
		}
		if err != nil {
			return stopArgoAfterError(ctx, client, initial, operationID, err)
		}
		if live.GetUID() != initial.GetUID() || live.GetAnnotations()[ArgoOperationAnnotation] != operationID {
			return live, fmt.Errorf("GitOps operation ownership changed while observing")
		}
		if !argoOperationActive(live) && argoOperationID(live, "status", "operationState", "operation") == operationID {
			if argoString(live, "status", "operationState", "phase") == "Succeeded" {
				return live, nil
			}
			return live, fmt.Errorf("argo CD sync did not succeed")
		}
		select {
		case <-ctx.Done():
		case <-ticker.C:
		}
	}
}

func stopArgoAfterError(ctx context.Context, client dynamic.ResourceInterface, initial *unstructured.Unstructured, operationID string, cause error) (*unstructured.Unstructured, error) {
	stopCtx, cancel := context.WithTimeout(context.WithoutCancel(ctx), 30*time.Second)
	defer cancel()
	stopped, err := terminateArgoOperation(stopCtx, client, initial, operationID)
	if err != nil {
		return stopped, fmt.Errorf("%w: %v", ErrArgoStopUnconfirmed, err)
	}
	if ctx.Err() != nil {
		cause = ctx.Err()
	}
	return stopped, cause
}

// The native Argo CD TerminateOperation implementation updates the root status
// phase to Terminating. UID/RV and operation identity fence every request here;
// only a controller-written terminal observation confirms the stop.
func terminateArgoOperation(ctx context.Context, client dynamic.ResourceInterface, initial *unstructured.Unstructured, operationID string) (*unstructured.Unstructured, error) {
	ticker := time.NewTicker(time.Second)
	defer ticker.Stop()
	for {
		live, err := client.Get(ctx, initial.GetName(), metav1.GetOptions{})
		if err != nil {
			return live, err
		}
		if live.GetUID() != initial.GetUID() || live.GetAnnotations()[ArgoOperationAnnotation] != operationID {
			return live, fmt.Errorf("GitOps operation identity changed before stop confirmation")
		}
		stateID := argoOperationID(live, "status", "operationState", "operation")
		phase := argoString(live, "status", "operationState", "phase")
		if !argoOperationActive(live) && stateID == operationID {
			if phase == "Succeeded" || phase == "Failed" {
				return live, nil
			}
			return live, fmt.Errorf("argo CD termination reported an error")
		}
		if live.Object["operation"] != nil && argoOperationID(live, "operation") != operationID {
			return live, fmt.Errorf("another GitOps operation is active")
		}
		if stateID == operationID && phase == "Running" {
			_ = unstructured.SetNestedField(live.Object, "Terminating", "status", "operationState", "phase")
			_, err = client.Update(ctx, live, metav1.UpdateOptions{})
			if err != nil && !apierrors.IsConflict(err) {
				return live, err
			}
		}
		select {
		case <-ctx.Done():
			return live, ctx.Err()
		case <-ticker.C:
		}
	}
}

func validateArgoProject(ctx context.Context, client dynamic.Interface, application *unstructured.Unstructured) error {
	namespace := application.GetAnnotations()["delivery.soha.io/argocd-namespace"]
	if namespace == "" {
		namespace = application.GetNamespace()
	}
	project, err := client.Resource(schema.GroupVersionResource{Group: "argoproj.io", Version: "v1alpha1", Resource: "appprojects"}).Namespace(namespace).Get(ctx, argoString(application, "spec", "project"), metav1.GetOptions{})
	if err != nil {
		return fmt.Errorf("read restricted Argo CD project: %w", err)
	}
	destinations, _, err := unstructured.NestedSlice(project.Object, "spec", "destinations")
	if err != nil || len(destinations) != 1 {
		return fmt.Errorf("GitOps project must authorize only the selected namespace and cluster")
	}
	destination, _ := destinations[0].(map[string]any)
	if destination["namespace"] != application.GetNamespace() || destination["server"] != "https://kubernetes.default.svc" {
		return fmt.Errorf("GitOps project destination is outside the delivery target")
	}
	clusterKinds, _, err := unstructured.NestedSlice(project.Object, "spec", "clusterResourceWhitelist")
	if err != nil || len(clusterKinds) != 0 {
		return fmt.Errorf("GitOps project must deny cluster-scoped resources")
	}
	allowed, _, err := unstructured.NestedSlice(project.Object, "spec", "namespaceResourceWhitelist")
	if err != nil || len(allowed) == 0 {
		return fmt.Errorf("GitOps project requires an explicit supported resource allowlist")
	}
	for _, raw := range allowed {
		item, _ := raw.(map[string]any)
		group, _ := item["group"].(string)
		kind, _ := item["kind"].(string)
		if _, ok := argoResourceTypes[group+"/"+kind]; !ok {
			return fmt.Errorf("GitOps project permits unsupported resource kinds")
		}
	}
	repositories, _, err := unstructured.NestedStringSlice(project.Object, "spec", "sourceRepos")
	if err != nil || !slices.Contains(repositories, argoString(application, "spec", "source", "repoURL")) {
		return fmt.Errorf("GitOps repository is not explicitly authorized by its project")
	}
	if namespace != application.GetNamespace() {
		sources, _, err := unstructured.NestedStringSlice(project.Object, "spec", "sourceNamespaces")
		if err != nil || !slices.Contains(sources, application.GetNamespace()) {
			return fmt.Errorf("GitOps project does not authorize this Application namespace")
		}
	}
	// Wildcard source access is not a sufficient substitute for an explicit grant.
	for _, repository := range repositories {
		if strings.ContainsAny(repository, "*?") {
			return fmt.Errorf("GitOps project repository grants must be explicit")
		}
	}
	return nil
}
