import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { parse, stringify } from "yaml";

const root = new URL("..", import.meta.url);
const checkOnly = process.argv.includes("--check");
const oapiCodegenVersion = "v2.7.1";

const outputs = [
  "gen/go/sohaapi/types.go",
  "gen/ts/sohaapi/index.ts",
];

const before = new Map();
if (checkOnly) {
  for (const path of outputs) {
    before.set(path, await readFile(new URL(path, root), "utf8").catch(() => ""));
  }
}

await mkdir(new URL("gen/go/sohaapi", root), { recursive: true });
await mkdir(new URL("gen/ts/sohaapi", root), { recursive: true });

run("npx", [
  "openapi-typescript",
  "openapi/soha-api.yaml",
  "--root-types",
  "--root-types-no-schema-prefix",
  "--root-types-keep-casing",
  "--output",
  "gen/ts/sohaapi/index.ts",
]);
await patchTypeScriptEntrypoint(new URL("gen/ts/sohaapi/index.ts", root));

const goSpecPath = await writeGoCompatibilitySpec();
run("go", [
  "run",
  `github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@${oapiCodegenVersion}`,
  "-config",
  "configs/oapi-codegen.yaml",
  "-o",
  "gen/go/sohaapi/types.go",
  goSpecPath,
]);
await patchGoEntrypoint(new URL("gen/go/sohaapi/types.go", root));
run("gofmt", ["-w", "gen/go/sohaapi/types.go"]);

if (checkOnly) {
  let changed = false;
  for (const path of outputs) {
    const current = await readFile(new URL(path, root), "utf8").catch(() => "");
    if (before.get(path) !== current) {
      changed = true;
      console.error(`${path} is out of date. Run npm run generate.`);
    }
  }
  if (changed) {
    for (const [path, content] of before) {
      const url = new URL(path, root);
      await mkdir(dirname(fileURLToPath(url)), { recursive: true });
      await writeFile(url, content);
    }
    throw new Error("generated SDK entrypoints are out of date");
  }
}

async function patchTypeScriptEntrypoint(url) {
  const generated = await readFile(url, "utf8");
  const patched = generated
    .replace(
      "/**\n * This file was auto-generated by openapi-typescript.\n * Do not make direct changes to the file.\n */",
      "// Code generated from OpenSoha contracts by openapi-typescript. DO NOT EDIT.",
    )
    .replace(
      "export type AnyValue = components['schemas']['AnyValue'];",
      [
        "export type AnyObject = Record<string, unknown>;",
        "export type ApiResponse<T = unknown> = { data: T };",
        "export type ApiItemsResponse<T = unknown> = { items: T[] };",
        "export type AuthTokens = TokenSet;",
        "export type AnyValue = components['schemas']['AnyValue'];",
      ].join("\n"),
    );
  await writeFile(url, patched);
}

async function patchGoEntrypoint(url) {
  let generated = await readFile(url, "utf8");
  generated = generated
    .replace(
      "// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version",
      "// Code generated from OpenSoha contracts by github.com/oapi-codegen/oapi-codegen/v2 version",
    )
    .replace("type AnyValue = interface{}", "type AnyValue = any")
    .replaceAll("map[string]interface{}", "map[string]any");
  await writeFile(url, generated);
}

async function writeGoCompatibilitySpec() {
  const specUrl = new URL("openapi/soha-api.yaml", root);
  const spec = parse(await readFile(specUrl, "utf8"));
  applyGoCompatibility(spec);

  const dir = await mkdtemp(join(tmpdir(), "opensoha-contracts-"));
  const path = join(dir, "soha-api.go.yaml");
  await writeFile(path, stringify(spec));
  return path;
}

function applyGoCompatibility(spec) {
  const schemas = spec?.components?.schemas ?? {};

  const riskLevel = schemas.RiskLevel;
  if (isObject(riskLevel)) {
    riskLevel["x-go-type"] = "string";
  }

  setPropertyGoType(schemas, "PluginManifest", "type", "string");
  setPropertyGoType(schemas, "InstalledPlugin", "status", "string");

  for (const schema of Object.values(schemas)) {
    markOptionalPointerFields(schema, schemas);
  }
}

function setPropertyGoType(schemas, schemaName, propertyName, typeName) {
  const property = schemas?.[schemaName]?.properties?.[propertyName];
  if (isObject(property)) {
    property["x-go-type"] = typeName;
  }
}

function markOptionalPointerFields(schema, schemas) {
  if (!isObject(schema)) {
    return;
  }

  const required = new Set(Array.isArray(schema.required) ? schema.required : []);
  const properties = isObject(schema.properties) ? schema.properties : {};
  for (const [name, property] of Object.entries(properties)) {
    if (!isObject(property)) {
      continue;
    }
    if (!required.has(name) && shouldKeepOptionalPointer(property, schemas)) {
      property["x-go-type-skip-optional-pointer"] = false;
    }
    markOptionalPointerFields(property, schemas);
  }

  if (isObject(schema.items)) {
    markOptionalPointerFields(schema.items, schemas);
  }
  if (isObject(schema.additionalProperties)) {
    markOptionalPointerFields(schema.additionalProperties, schemas);
  }
  for (const composition of ["allOf", "anyOf", "oneOf"]) {
    const entries = schema[composition];
    if (Array.isArray(entries)) {
      for (const entry of entries) {
        markOptionalPointerFields(entry, schemas);
      }
    }
  }
}

function shouldKeepOptionalPointer(property, schemas) {
  if (property["x-go-pointer"] === true) {
    return true;
  }
  if (property.type === "string" && property.format === "date-time") {
    return true;
  }
  if (property.$ref) {
    const refName = getRefName(property.$ref);
    if (refName === "JSONSchema") {
      return false;
    }
    const refSchema = schemas[refName];
    return isSchemaObject(refSchema);
  }
  if (property.type === "object" && (isObject(property.properties) || property.additionalProperties === false)) {
    return true;
  }
  return false;
}

function getRefName(ref) {
  return ref.split("/").at(-1);
}

function isSchemaObject(schema) {
  return isObject(schema) && (schema.type === "object" || isObject(schema.properties));
}

function isObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: fileURLToPath(root),
    encoding: "utf8",
    stdio: "pipe",
  });
  const output = `${result.stdout ?? ""}${result.stderr ?? ""}`;
  if (result.status !== 0) {
    throw new Error(`${command} ${args.join(" ")} failed\n${output}`);
  }
  if (output.trim()) {
    console.error(output.trim());
  }
}
